// TODO: consider nesting under reducerName or breaking out files
export default {
  CREATE_SESSION: 'CREATE_SESSION',
  UPDATE_SESSION_IS_ACTIVE_SEAT: 'UPDATE_SESSION_IS_ACTIVE_SEAT',
  UPDATE_SESSION_TOTAL_SEATS: 'UPDATE_SESSION_TOTAL_SEATS',
  UPDATE_SESSION_LOCATION: 'UPDATE_SESSION_LOCATION',
  UPDATE_SESSION_HERO_SEAT_INDEX: 'UPDATE_SESSION_HERO_SEAT_INDEX',

  CREATE_HAND: 'CREATE_HAND',
  SET_HERO_CARDS: 'SET_HERO_CARDS'
};